remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "mint"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/islandora"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/Islandora/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/islandora-community/IslandoraCon2022"

plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
